MODEL:
  ARCH: resnet50
  PROJECTION:
    EMB_DIM: 2048
  
INPUT:
  SIZE: (224, 224)
  
CORRUPTION:
  DATASET: imagenet_c_bar
  NUM_CLASS: 1000
  NUM_EX: 5000
  SEVERITY:
    - 5
  TYPE:
    - 'blue_noise'
    - 'brownish_noise'
    - 'caustic_refraction'
    - 'checkerboard_cutout'
    - 'cocentric_sine_waves'
    - 'inverse_sparkles'
    - 'perlin_noise'
    - 'plasma_noise'
    - 'single_frequency_greyscale'
    - 'sparkles'